train:
  export_path: 
  train_tag:
  gpu: 0
  epochs: 15
  lr: 1e-4
  batch_size: 256
  save_interval: 5
  train_ratio: 0.8

data:
  normalize: True
  weights_path: "./data/all_weights.pt"

model:
  vae:
    latent_dim: 1024
    hidden_dim: 1024
    blocks: 1
    kl_beta: 0.1